services:
  database:
    container_name: acs-core-database
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./databasepg:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  core-services:
    container_name: acs-core-services
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: acs-core-database
      DB_PORT: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      APP_PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
