services:
  database:
    container_name: acs-core-database
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Bangkok
    command:
      - "postgres"
      - "-c"
      - "timezone=Asia/Bangkok"

    ports:
      - "5432:5432"
    volumes:
      - ./databasepg:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  core-services:
    container_name: acs-core-services
    build:
      context: .
      dockerfile: dockerfile
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_BUCKET: ${SUPABASE_BUCKET}
      DB_HOST: acs-core-database
      DB_PORT: 5432
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@acs-core-database:5432/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      APP_PORT: ${APP_PORT}
      APP_HOST: 0.0.0.0
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
